apiVersion: v1
kind: Secret
metadata:
  name: maas-service-secret{{ .Values.prototypeSignature }}
  labels:
    app: maas{{ .Values.prototypeSignature }}
    module: maas-service{{ .Values.prototypeSignature }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.databaseUsername | b64enc }}
  DATABASE_PASSWORD: {{ .Values.databasePassword | b64enc }}
  SECRET_KEY: {{ .Values.serviceSecretKey | b64enc }}
