apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-service-account{{ .Values.prototypeSignature }}
  labels:
    app: maas{{ .Values.prototypeSignature }}
    module: maas-service{{ .Values.prototypeSignature }}
imagePullSecrets:
- name: {{ .Values.imagePullSecretName }}
