apiVersion: v1
kind: Service
metadata:
  name: maas-service{{ .Values.prototypeSignature }}
  labels:
    app: maas{{ .Values.prototypeSignature }}
    module: maas-service{{ .Values.prototypeSignature }}
spec:
  selector:
    module: maas-service{{ .Values.prototypeSignature }}
  ports:
    - port: 8000
      targetPort: 8000
