apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-service-config{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-service{{ .Values.prototypeSignature }}
data:
  DEBUG: "False"
  DATABASE_ENGINE: "postgresql"
  DATABASE_NAME: "orchestrator"
  DATABASE_HOST: "orchestrator-database-service{{ .Values.prototypeSignature }}"
  DATABASE_PORT: "5432"
  ALLOWED_HOSTS: "orchestrator-service{{ .Values.prototypeSignature }},orchestrator-service{{ .Values.prototypeSignature }}.{{ .Release.Namespace }}.svc.cluster.local"
  MAAS_API_HOSTNAME: "maas-service{{ .Values.prototypeSignature }}:8000"
  ORCHESTRATOR_API_HOSTNAME: "orchestrator-service{{ .Values.prototypeSignature }}:8000"
  VALID_DATA_PARTNERS: "uns,uns-rm2,auth,auth-rm2,uoa,uoa-rm2,hcs-rm2"
  VALIDATE_WITH_MAAS: "true"
  
  PLATFORM_CENTRAL_NODE_LABEL_KEY: "{{ .Values.centralNodeLabelKey }}"
  PLATFORM_CENTRAL_NODE_LABEL_VALUE: "{{ .Values.centralNodeLabelValue }}"
  
  PROCESSOR_RESOURCE_MANAGER_VERSION: "{{ .Values.processorResourceManagerImageVersion }}"
  PROCESSOR_RESOURCE_MANAGER_API_HOST: "{{ .Values.processorResourceManagerApiHost }}"
  PROCESSOR_RESOURCE_MANAGER_CALLBACK_URL: "{{ .Values.processorResourceManagerCallbackUrl }}"
  
  FEDERATED_LEARNING_MANAGER_VERSION: "{{ .Values.federatedLearningManagerImageVersion }}"
  
  AI_ENGINE_PLATFORM_VARS_CONFIG_MAP_NAME: "ai-engine-config{{ .Values.prototypeSignature }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_ELEMENTS: "{{ .Values.plaformVarsInputElements }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_DATA_TRAINING_TABULAR: "{{ .Values.plaformVarsInputDataTrainingTabular }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_DATA_TRAINING_IMAGERY: "{{ .Values.plaformVarsInputDataTrainingImagery }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_DATA_EVALUATION_TABULAR: "{{ .Values.plaformVarsInputDataEvaluationTabular }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_DATA_EVALUATION_IMAGERY: "{{ .Values.plaformVarsInputDataEvaluationImagery }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_DATA_INFERENCE: "{{ .Values.plaformVarsInputDataInference }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_DATA_INFERENCE_REPORT_METADATA: "{{ .Values.plaformVarsInputDataInferenceReportMetadata }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_AI_ELEMENTS: "{{ .Values.plaformVarsAIElements }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_USER_VARS: "{{ .Values.plaformVarsInputUserVars }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_MODEL: "{{ .Values.plaformVarsInputModel }}"
  AI_ENGINE_PLATFORM_VARS_INPUT_MODELS: "{{ .Values.plaformVarsInputModels }}"
  AI_ENGINE_PLATFORM_VARS_OUTPUT_ELEMENTS: "{{ .Values.plaformVarsOutputElements }}"
  AI_ENGINE_PLATFORM_VARS_OUTPUT_MODEL: "{{ .Values.plaformVarsOutputModel }}"
  AI_ENGINE_PLATFORM_VARS_OUTPUT_EVALUATION_METRICS: "{{ .Values.plaformVarsOutputEvaluationMetrics }}"
  AI_ENGINE_PLATFORM_VARS_OUTPUT_INFERENCE_RESULTS: "{{ .Values.plaformVarsOutputInferenceResults }}"
  AI_ENGINE_PLATFORM_VARS_API_PING_URL: "{{ .Values.plaformVarsApiPingUrl }}"
  AI_ENGINE_PLATFORM_VARS_API_RUN_URL: "{{ .Values.plaformVarsApiRunUrl }}"
  AI_ENGINE_PLATFORM_VARS_API_END_URL: "{{ .Values.plaformVarsApiEndUrl }}"
  AI_ENGINE_PLATFORM_VARS_API_HOST: "{{ .Values.plaformVarsApiHost }}:{{ .Values.plaformVarsApiPort }}"
  
  ARGO_WORKFLOWS_API_HOST: "https://argo-workflows-server.argo-workflows.svc.cluster.local:2746"
  ARGO_WORKFLOWS_NAMESPACE: "{{ .Release.Namespace }}"
  
  COMMUNICATION_ADAPTER: "kafka"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafkaBootstrapServers }}"
  KAFKA_MAX_MODEL_SIZE: "{{ .Values.maxModelSize }}"
