apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-service-secret{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-service{{ .Values.prototypeSignature }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.databaseUsername | b64enc }}
  DATABASE_PASSWORD: {{ .Values.databasePassword | b64enc }}
  SECRET_KEY: {{ .Values.serviceSecretKey | b64enc }}
