apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-service-account{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-service{{ .Values.prototypeSignature }}
imagePullSecrets:
  - name: incisive-azurecrio-secret
