apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-service{{ .Values.prototypeSignature }}
spec:
  selector:
    module: orchestrator-service{{ .Values.prototypeSignature }}
  ports:
    - port: 8000
      targetPort: 8000
