apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-service-storage-claim{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-service{{ .Values.prototypeSignature }}
spec:
  {{- if eq .Values.localInference.enabled true }}
  {{- with .Values.localInference }}
  storageClassName: orchestrator-local-storage
  volumeName: orchestrator-service-pv-{{ .hostname }}
  {{- end }}
  {{- else }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
