apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: "2"
      limits:
        memory: 2Gi
        cpu: "4"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: persistent-claim
      size: 10Gi
      class: {{ .Values.storageClassName }}
      deleteClaim: false
    config:
      max.request.size: 1000000000
      message.max.bytes: 1000000000
      max.partition.fetch.bytes: 1000000000
      replica.fetch.max.bytes: 1000000000
      fetch.message.max.bytes: 1000000000
      session.timeout.ms: 240000
      auto.create.topics.enable: "false"
      log.cleaner.enable: "true"
      log.cleanup.policy: "compact,delete"
      log.retention.check.interval.ms: 2000000
      log.retention.ms: 1800000
      log.cleaner.delete.retention.ms: 0
      log.segment.delete.delay.ms: 0
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "2"    
    storage:
      type: persistent-claim
      size: 10Gi
      class: {{ .Values.storageClassName }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
