apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-database-config{{ .Values.prototypeSignature }}
  labels:
    app: maas{{ .Values.prototypeSignature }}
    module: maas-database{{ .Values.prototypeSignature }}
data:
  POSTGRES_DB: "maas"
  PGDATA: "/var/lib/postgresql/data/pgdata"
