apiVersion: v1
kind: Secret
metadata:
  name: maas-database-secret{{ .Values.prototypeSignature }}
  labels:
    app: maas{{ .Values.prototypeSignature }}
    module: maas-database{{ .Values.prototypeSignature }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.databaseUsername | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.databasePassword | b64enc }}
