apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maas-database{{ .Values.prototypeSignature }}
  labels:
    app: maas{{ .Values.prototypeSignature }}
    module: maas-database{{ .Values.prototypeSignature }}
spec:
  {{- if eq .Values.localInference.enabled true }}
  {{- with .Values.localInference }}
  storageClassName: maas-local-storage
  volumeName: maas-database-pv-{{ .hostname }}
  {{- end }}
  {{- else }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
