apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-database-config{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-database{{ .Values.prototypeSignature }}
data:
  POSTGRES_DB: "orchestrator"
  PGDATA: "/var/lib/postgresql/data/pgdata"
