apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-database-secret{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-database{{ .Values.prototypeSignature }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.databaseUsername | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.databasePassword | b64enc }}
