apiVersion: v1
kind: Service
metadata:
  name: orchestrator-database-service{{ .Values.prototypeSignature }}
  labels:
    app: orchestrator{{ .Values.prototypeSignature }}
    module: orchestrator-database{{ .Values.prototypeSignature }}
spec:
  selector:
    module: orchestrator-database{{ .Values.prototypeSignature }}
  ports:
    - port: 5432
      targetPort: 5432
